apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
  namespace: ${REGISTRY_NAME}
spec:
  secretName: app-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ${DOMAIN_NAME}.${DOMAIN_SUFFIX}
  privateKey:
    algorithm: RSA
    size: 2048 