apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CACHE_UPDATER_NAME:cache-updater}
  labels:
    app: ${CACHE_UPDATER_NAME:cache-updater}
spec:
  replicas: ${BACKEND_REPLICAS}
  selector:
    matchLabels:
      app: ${CACHE_UPDATER_NAME:cache-updater}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ${CACHE_UPDATER_NAME:cache-updater}
    spec:
      imagePullSecrets:
        - name: registry-credentials
      initContainers:
        - name: wait-for-redis
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: ${CACHE_UPDATER_NAME:cache-updater}
          image: ${REGISTRY}/${REGISTRY_NAME}/${CACHE_UPDATER_NAME:cache-updater}:${VERSION}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: cache-updater-config
          env:
            - name: GITHUB_TOKENS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: github.tokens
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: ${BACKEND_REQUEST_MEMORY}
              cpu: ${BACKEND_REQUEST_CPU}
            limits:
              memory: ${BACKEND_LIMIT_MEMORY}
              cpu: ${BACKEND_LIMIT_CPU}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: ${SERVER_PORT}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: ${SERVER_PORT}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3 