apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-updater
  labels:
    app: cache-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-updater
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cache-updater
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: cache-updater
          image: ${REGISTRY}/${REGISTRY_NAME}/cache-updater:${VERSION}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: GITHUB_TOKENS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: github.tokens
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: ${BACKEND_REQUEST_MEMORY}
              cpu: ${BACKEND_REQUEST_CPU}
            limits:
              memory: ${BACKEND_LIMIT_MEMORY}
              cpu: ${BACKEND_LIMIT_CPU}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3 