apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: ${ENVIRONMENT:-production}
  DOMAIN_NAME: ${DOMAIN_NAME:-major-league-github}
  BACKEND_URL: ${BACKEND_URL:-http://backend-service:8450}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_OPTS: "-Xmx${JAVA_MAX_HEAP:-1536m} -Xms${JAVA_MIN_HEAP:-768m} -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: ${NODE_ENV:-production}
  API_TIMEOUT: ${API_TIMEOUT:-30000}
---
# Template for required secrets - DO NOT store actual values here
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  GITHUB_TOKENS: ${GITHUB_TOKENS_BASE64}
  SSL_CERT_KEY: ${SSL_CERT_KEY_BASE64}
  SSL_CERT: ${SSL_CERT_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_BASE64} 