apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  BACKEND_URL: "http://${WEB_SERVICE_NAME}-service:${WEB_SERVICE_PORT}"
  DOMAIN_NAME: "${DOMAIN_NAME}"
  ENVIRONMENT: "${ENVIRONMENT}"
  JAVA_OPTS: "-Xmx${JAVA_MAX_HEAP} -Xms${JAVA_MIN_HEAP} -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  CACHE_IMPLEMENTATION: "redis"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${WEB_SERVICE_NAME}-config
data:
  SERVER_PORT: "${WEB_SERVICE_PORT}"
  SPRING_PROFILES_ACTIVE: "${WEB_SERVICE_NAME}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CACHE_UPDATER_NAME}-config
data:
  SERVER_PORT: "${CACHE_UPDATER_PORT}"
  SPRING_PROFILES_ACTIVE: "${CACHE_UPDATER_NAME}"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  github.tokens: "${GH_API_TOKENS}"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "${DOCKER_CONFIG_BASE64}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: "${NODE_ENV:-production}"
  API_TIMEOUT: "${API_TIMEOUT:-30000}" 