apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: ${FRONTEND_REPLICAS}
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: frontend
          image: ${REGISTRY}/${REGISTRY_NAME}/frontend:${VERSION}
          imagePullPolicy: Always
          env:
            - name: OG_TITLE
              value: "${OG_TITLE}"
            - name: OG_DESCRIPTION
              value: "${OG_DESCRIPTION}"
            - name: OG_TYPE
              value: "${OG_TYPE}"
            - name: OG_IMAGE_URL
              value: "${OG_IMAGE_URL}"
            - name: OG_URL
              value: "https://${DOMAIN_NAME}.${DOMAIN_SUFFIX}"
            - name: OG_SITE_NAME
              value: "${OG_SITE_NAME}"
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 80
              name: http
            - containerPort: 81
              name: health
          resources:
            requests:
              memory: ${FRONTEND_REQUEST_MEMORY}
              cpu: ${FRONTEND_REQUEST_CPU}
            limits:
              memory: ${FRONTEND_LIMIT_MEMORY}
              cpu: ${FRONTEND_LIMIT_CPU}
          startupProbe:
            httpGet:
              path: /nginx-health
              port: health
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: health
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP 