apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  labels:
    app: web-service
spec:
  replicas: ${BACKEND_REPLICAS}
  selector:
    matchLabels:
      app: web-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: web-service
    spec:
      imagePullSecrets:
        - name: registry-credentials
      initContainers:
        - name: wait-for-redis
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: web-service
          image: ${REGISTRY}/${REGISTRY_NAME}/web-service:${VERSION}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: web-service-config
          env:
            - name: GITHUB_TOKENS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: github.tokens
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: ${BACKEND_REQUEST_MEMORY}
              cpu: ${BACKEND_REQUEST_CPU}
            limits:
              memory: ${BACKEND_LIMIT_MEMORY}
              cpu: ${BACKEND_LIMIT_CPU}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-service
spec:
  selector:
    app: web-service
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP 