apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: registry-major-league-github
      containers:
      - name: backend
        image: registry.digitalocean.com/major-league-github/major-league-github-backend:latest
        ports:
        - containerPort: 8450
        env:
        - name: github.tokens
          valueFrom:
            secretKeyRef:
              name: github-tokens
              key: github.tokens
        - name: JAVA_TOOL_OPTIONS
          value: "-Xmx1536m -Xms768m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "2.5Gi"
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8450
      targetPort: 8450
  type: ClusterIP 